name: on-dev-push
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        uses: actions/setup-node@v1
        run: npm i
        run: npm run lint
